require 'dzl/examples/base'

class Dzl::Examples::RouteProfile < Dzl::Examples::base
  global_pblock do end

  #150 routes
  endpoint '/Lorem' do end
  endpoint '/ipsum' do end
  endpoint '/dolor' do end
  endpoint '/sit' do end
  endpoint '/amet' do end
  endpoint '/consectetur' do end
  endpoint '/adipiscing' do end
  endpoint '/elit' do end
  endpoint '/Aenean' do end
  endpoint '/pulvinar' do end
  endpoint '/ante' do end
  endpoint '/id' do end
  endpoint '/venenatis' do end
  endpoint '/eleifend' do end
  endpoint '/Vivamus' do end
  endpoint '/mattis' do end
  endpoint '/tempor' do end
  endpoint '/bibendum' do end
  endpoint '/nulla' do end
  endpoint '/lobortis' do end
  endpoint '/vitae' do end
  endpoint '/Vestibulum' do end
  endpoint '/primis' do end
  endpoint '/in' do end
  endpoint '/faucibus' do end
  endpoint '/orci' do end
  endpoint '/luctus' do end
  endpoint '/et' do end
  endpoint '/ultrices' do end
  endpoint '/posuere' do end
  endpoint '/cubilia' do end
  endpoint '/Curae;' do end
  endpoint '/Proin' do end
  endpoint '/nisi' do end
  endpoint '/malesuada' do end
  endpoint '/eu' do end
  endpoint '/scelerisque' do end
  endpoint '/ut' do end
  endpoint '/eget' do end
  endpoint '/augue' do end
  endpoint '/Aliquam' do end
  endpoint '/erat' do end
  endpoint '/volutpat' do end
  endpoint '/Praesent' do end
  endpoint '/leo' do end
  endpoint '/commodo' do end
  endpoint '/ac' do end
  endpoint '/suscipit' do end
  endpoint '/sed' do end
  endpoint '/magna' do end
  endpoint '/Fusce' do end
  endpoint '/lacinia' do end
  endpoint '/lorem' do end
  endpoint '/felis' do end
  endpoint '/fermentum' do end
  endpoint '/non' do end
  endpoint '/molestie' do end
  endpoint '/ligula' do end
  endpoint '/sollicitudin' do end
  endpoint '/Cras' do end
  endpoint '/auctor' do end
  endpoint '/mi' do end
  endpoint '/eros' do end
  endpoint '/quis' do end
  endpoint '/velit' do end
  endpoint '/facilisis' do end
  endpoint '/a' do end
  endpoint '/metus' do end
  endpoint '/Ut' do end
  endpoint '/enim' do end
  endpoint '/aliquam' do end
  endpoint '/cursus' do end
  endpoint '/Etiam' do end
  endpoint '/imperdiet' do end
  endpoint '/rhoncus' do end
  endpoint '/nibh' do end
  endpoint '/tincidunt' do end
  endpoint '/ullamcorper' do end
  endpoint '/Nulla' do end
  endpoint '/dapibus' do end
  endpoint '/nunc' do end
  endpoint '/at' do end
  endpoint '/vestibulum' do end
  endpoint '/tortor' do end
  endpoint '/pharetra' do end
  endpoint '/vulputate' do end
  endpoint '/accumsan' do end
  endpoint '/Pellentesque' do end
  endpoint '/Nam' do end
  endpoint '/elementum' do end
  endpoint '/ultricies' do end
  endpoint '/Morbi' do end
  endpoint '/varius' do end
  endpoint '/lacus' do end
  endpoint '/mollis' do end
  endpoint '/Quisque' do end
  endpoint '/porttitor' do end
  endpoint '/arcu' do end
  endpoint '/mauris' do end
  endpoint '/hendrerit' do end
  endpoint '/pretium' do end
  endpoint '/placerat' do end
  endpoint '/quam' do end
  endpoint '/feugiat' do end
  endpoint '/diam' do end
  endpoint '/aliquet' do end
  endpoint '/convallis' do end
  endpoint '/Donec' do end
  endpoint '/dignissim' do end
  endpoint '/lectus' do end
  endpoint '/rutrum' do end
  endpoint '/nisl' do end
  endpoint '/ornare' do end
  endpoint '/tristique' do end
  endpoint '/sapien' do end
  endpoint '/euismod' do end
  endpoint '/vel' do end
  endpoint '/massa' do end
  endpoint '/porta' do end
  endpoint '/nec' do end
  endpoint '/habitant' do end
  endpoint '/morbi' do end
  endpoint '/senectus' do end
  endpoint '/netus' do end
  endpoint '/fames' do end
  endpoint '/turpis' do end
  endpoint '/egestas' do end
  endpoint '/Curabitur' do end
  endpoint '/pellentesque' do end
  endpoint '/libero' do end
  endpoint '/Duis' do end
  endpoint '/congue' do end
  endpoint '/iaculis' do end
  endpoint '/In' do end
  endpoint '/Nunc' do end
  endpoint '/Sed' do end
  endpoint '/blandit' do end
  endpoint '/tempus' do end
  endpoint '/tellus' do end
  endpoint '/condimentum' do end
  endpoint '/interdum' do end
  endpoint '/fringilla' do end
  endpoint '/viverra' do end
  endpoint '/justo' do end
  endpoint '/consequat' do end
  endpoint '/gravida' do end
  endpoint '/risus' do end
  endpoint '/urna' do end
  endpoint '/semper' do end
  endpoint '/dui' do end

end